name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    name: Install dependencies
    
    steps:
    - uses: actions/checkout@v1
    - name: Composer install
      uses: php-actions/composer@master
