name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Install dependencies
    steps:
    - name: Composer install
      id: composer-install
      uses: php-actions/composer@v0.0.1
